import { StyleSheet, Dimensions } from "react-native";
const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
  main: {
    flex: 1,
    backgroundColor: "#F8FDFF",
    padding: 16,
  },
  background: {
    width,
    height,
    position: "absolute",
  },
  title: {
    textAlign: "center",
    fontSize: 20,
    lineHeight: 35,
    fontWeight: "800",
    color: "#3586AB",
  },
  subtitle: {
    marginTop: 17,
    marginBottom: 16,
    textAlign: "center",
    fontSize: 24,
    lineHeight: 35,
    fontWeight: "500",
    color: "#005B85",
  },
  imgContainer: {
    backgroundColor: "#005B85",
    margin: 26,
    width: 322,
    height: 173,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
  },
  imgText: {
    color: "#FFFFFF",
    fontWeight: "500",
    fontSize: 14,
    lineHeight: 18,
  },
  img: { width: 322, height: 173, borderRadius: 12 },
  text: {
    marginTop: 16,
    marginBottom: 80,
    textAlign: "center",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "400",
    color: "#005B85",
  },
  finish: {
    justifyContent: "center",
    width: 255,
    height: 48,
    alignItems: "center",
    marginLeft: "auto",
    marginRight: "auto",
    borderRadius: 50,
    backgroundColor: "#005B85",
  },
  finishText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 21.86,
    fontWeight: "900",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.3)",
  },
  modalView: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 16,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalButtons: {
    flexDirection: "row",
  },
  modalButton: {
    borderRadius: 50,
    elevation: 2,
    width: 120,
    height: 48,
    margin: 10,
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#005B85",
    borderWidth: 1.5,
  },
  modalButtonClose: {
    backgroundColor: "#E05457",
    borderWidth: 0,
  },
  modalButtonText: {
    color: "white",
    fontWeight: "bold",
  },
  modalText: {
    marginBottom: 15,
    textAlign: "center",
  },
});
